name: arsons
description: "An inventory and PDF generation app for Sanitary and Tile Store"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  get_storage: ^2.1.1
  pdf: ^3.11.1
  printing: ^5.13.2
  intl: ^0.20.2
  google_fonts: ^6.2.1
  arabic_reshaper: ^0.0.1
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icon.jpg"
    icon_size: 48
  image_path: "assets/icon.jpg"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon.jpg
    - assets/fonts/

  fonts:
    - family: JameelNooriNastaleeq
      fonts:
        - asset: assets/fonts/JameelNooriNastaleeq.ttf
